name: tscBuild
# You may pin to the exact commit or the version.
# uses: github-actions-x/commit@5cf7985b07155682f82d02b6c2188d90cebeb0c8

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  rollup-build:
    name: Builds `dist` and generate `docs`
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '🔨 @ ')"
    steps:
      # Gets the latest commit
      - uses: actions/checkout@v1
      # Setup node env
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      # npm install stuff
      - name: Install all dependencies
        run: |
          npm install
      # TypeScript Build
      - name : TypeScript Build
        run: |
          npm run-script build
      # TypeScript Build
      - name : Generate Docs
        run: |
          npm run-script doc
      # Set date and time of builds
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::🔨 @ $(date +'%Y-%m-%dT%H:%M:%S')"
      # Commit the stuff?
      - name: GitHub Commit & Push, If there is stuff to commit
        uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.BUILD_TOKEN }}
          message: ${{ steps.date.outputs.date }}

